### ISSUE TITLE
“Naupio” 和 “youenough”打赌，五年后 Rust 会有今天 Go 在中国那样火~

### ISSUE THREAD

**Issue by Naupio** [rustcc/WagerRust#1]
日期：2016-05-06——2021-05-06
输的一方，送对方一份大礼。
立 Issue 为证
量化标准：
既然是中国热度，以百度指数为准。还可以以 IT 岗位为参考
以下是 go 语言 2016-04-03 至 2016-05-02 全国整体搜索指数
golang 889
go语言 703
go 1905

以下是 rust 语言 2016-04-03 至 2016-05-02 全国整体搜索指数
rust 1335
ps: rustlang rust语言没有被收录词条

**Comment by wayslog** [comment]
前排留名

**Comment by youenough** [comment]
excited.

**Comment by wayslog** [comment]
你们啊…总想搞个大新闻…

**Comment by MarisaKirisame** [comment]
先说好怎么量化吧，比如搜索结果？

**Comment by Naupio** [comment]
既然是中国热度，按照百度指数吧~！

**Comment by miketang84** [comment]
赞。

**Comment by timqian** [comment]
啥大礼？

**Comment by douglarek** [comment]
放心吧 Rust 火不起来

**Comment by miketang84** [comment]
ls也来打赌嘛。绝对火。

**Comment by lucklove** [comment]
留名，要是火了叫我

**Comment by dovahcrow** [comment]
留名

**Comment by guotie** [comment]
不太可能。rust比go难很多

**Comment by dyxushuai** [comment]
火有点难，无法大众化，go基本开箱即用

**Comment by miketang84** [comment]
一个类似spark的东西出来，性能爆棚的话，瞬间火。

**Comment by chiyiw** [comment]
已经开始关注，不晚，纯粹好奇

**Comment by 3442853561** [comment]
火钳刘明

**Comment by DCjanus** [comment]
火钳刘明

**Comment by ARwMq9b6** [comment]
5 年很长哦，我认为用不了 5 年。

**Comment by CreatorMetaSky** [comment]
期盼中...，赶紧入坑 👍

**Comment by 2efPer** [comment]
一颗赛艇。留个名

**Comment by yyyy7** [comment]
haha😂

**Comment by Achieve777** [comment]
火钳刘明

**Comment by LivesMountain** [comment]
1111

**Comment by jeenlee** [comment]
知乎观光团前来报道

**Comment by ghost** [comment]
知乎观光团到此一游

**Comment by epver** [comment]
知乎观光团，下注go，rust不是游戏吗？

**Comment by li-sky** [comment]
知乎观光团到！
# 233333

**Comment by dyxushuai** [comment]
@cheneyliu go排名已经前10了

**Comment by coolulu** [comment]
然后直播吃啥？

**Comment by wayslog** [comment]
@DCjanus ，你搞起来的观光团。。。

**Comment by huangy10** [comment]
来让我们见证历史

**Comment by DCjanus** [comment]
我错了，已经删除知乎回答

**Comment by youngchan919** [comment]
用百度指数的话会面临一个问题，就是五年后百度还在吗（TX~）

**Comment by versee** [comment]
前排留名

**Comment by crazy-cpu** [comment]
冒个泡  见者有份呢

**Comment by xiaods** [comment]
冒个泡 见者有份呢

**Comment by ZhangHanDong** [comment]
我赌：Rust必火

**Comment by yjhmelody** [comment]
刚开始学，感觉基础设施好好造，应该可以流行起来。

**Comment by li-sky** [comment]
go似乎越来越火了。

**Comment by marswong** [comment]
@Naupio 中国热度用“百度指数”。。。

**Comment by xcorpio** [comment]
🉑

**Comment by Folyd** [comment]
Rust 比 Go 门槛高多了，希望能火吧

**Comment by XanthusL** [comment]
留个名，假装见者有份

**Comment by xiaods** [comment]
留个名，假装见者有份

**Comment by DCjanus** [comment]
加个参与者
![](https://i.imgur.com/7Wszcbv.jpg)

**Comment by shyangs** [comment]
为了赌约, LZ要多开几个Rust玩具项目贡献心力呀

**Comment by motecshine** [comment]
![image](https://user-images.githubusercontent.com/7615270/50532157-28203780-0b50-11e9-84cd-642ee8b3046b.png)

**Comment by luojia65** [comment]
:+1: 有希望火一把

**Comment by qioshikoyi** [comment]
rust上手难度那么大,凭什么能火

**Comment by wujunze** [comment]
我挺 Rust  6年以后 中国能火

**Comment by dingjun84** [comment]
rust火是有点难，希望能不温不火。

**Comment by swnb** [comment]
Rust 是门好语言, 但是比 Go 难写多了, 能像 Go 一样火不太现实吧...

**Comment by duguying** [comment]
后排留名

**Comment by ZhangHanDong** [comment]
发几个国家的google趋势数据，百度垃圾不能看

![image](https://user-images.githubusercontent.com/27893/57440481-afa65180-727a-11e9-8a5b-b7f82c69a87e.png)
![image](https://user-images.githubusercontent.com/27893/57440537-c5b41200-727a-11e9-9934-40e7e50adb23.png)
![image](https://user-images.githubusercontent.com/27893/57440541-c8af0280-727a-11e9-9e4f-991d0772a84a.png)
![image](https://user-images.githubusercontent.com/27893/57440549-ccdb2000-727a-11e9-87f7-2d0bd1fa97d3.png)
![image](https://user-images.githubusercontent.com/27893/57440573-d6fd1e80-727a-11e9-866b-2f7db6e50b42.png)
![image](https://user-images.githubusercontent.com/27893/57440578-dbc1d280-727a-11e9-9d4a-b3bfdbe6db2f.png)
![image](https://user-images.githubusercontent.com/27893/57440588-de242c80-727a-11e9-9982-df9abcf6fdba.png)

**Comment by hhwyt** [comment]
火钳刘明

**Comment by ZhangHanDong** [comment]
![rust-forth](https://user-images.githubusercontent.com/27893/57906933-4e9c0080-78ae-11e9-8e5e-7d96e8cbe13a.png)
Rust四周年啦，两年后必火
![rust-wqt](https://user-images.githubusercontent.com/27893/57906944-522f8780-78ae-11e9-8016-4697e6ab5878.png)

**Comment by micfan** [comment]
Golang快速开发
Rust极致开发

**Comment by jinleileiking** [comment]
不会比go热

**Comment by caibirdme** [comment]
应该不会的，越简单的语言越有市场，不管语言如何，看看PHP多流行。只要能用来方便地写curd，其它语言基本上就不太可能能超越它。如果性能再好一些比如Java和Go，基本上在业务开发上没啥对手了。但是Rust应该会像scala一样，被越来越多的人熟知，在某些领域开始独领风骚。毕竟通用软件或者底层系统远不如业务系统有那样多的需求

**Comment by duval1024** [comment]
我感觉rust用来写业务系统的可读性不够高，也不够快

**Comment by foonsun** [comment]
我支持RUST。

**Comment by zzhaolei** [comment]
还有一年，等待中...

**Comment by hsiaosiyuan0** [comment]
礼物可以先准备起来了

**Comment by captavia** [comment]
5年之约~

**Comment by luojia65** [comment]
这波我押RUAst（滑稽

**Comment by fifteen42** [comment]
虽然想支持 Rust，但热度应该是比不上 Go 吧

**Comment by duval1024** [comment]
看来rust要来不及了

**Comment by hbuxiaofei** [comment]
mark

**Comment by Naupio** [comment]
@youenough 发个联系方式给我？我感觉我差不多要准备份礼物给你了

**Comment by seanlees** [comment]
2021年4月22日，golang比rust火太多

**Comment by yjhmelody** [comment]
> 2021年4月22日，golang比rust火太多

人家是跟16年的golang比

**Comment by miketang84** [comment]
哈哈哈。感觉也不公平。

**Comment by inshyma** [comment]
**送礼了么?  特意回来看的**

**Comment by foonsun** [comment]
有啥好比的，自己用不爽吗

inshyma ***@***.***> 于2021年7月21日周三 下午4:38写道：
